# Task
can we predict the specific story that a news article refers to, given only its headline?

In [3]:
import pandas as pd
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import matplotlib.pyplot as plt


In [4]:
df = pd.read_csv(r'C:\Users\hp\Desktop\BIA main 2\uci-news-aggregator.csv')




In [5]:
df.head()

ID                                              TITLE  \
0   1  Fed official says weak data caused by weather,...   
1   2  Fed's Charles Plosser sees high bar for change...   
2   3  US open: Stocks fall after Fed official hints ...   
3   4  Fed risks falling 'behind the curve', Charles ...   
4   5  Fed's Plosser: Nasty Weather Has Curbed Job Gr...   

                                                 URL          PUBLISHER  \
0  http://www.latimes.com/business/money/la-fi-mo...  Los Angeles Times   
1  http://www.livemint.com/Politics/H2EvwJSK2VE6O...           Livemint   
2  http://www.ifamagazine.com/news/us-open-stocks...       IFA Magazine   
3  http://www.ifamagazine.com/news/fed-risks-fall...       IFA Magazine   
4  http://www.moneynews.com/Economy/federal-reser...          Moneynews   

  CATEGORY                          STORY             HOSTNAME      TIMESTAMP  
0        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM      www.latimes.com  1394470370698  
1        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM     www.livemint.com  1394470371207  
2        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371550  
3        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371793  
4        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM    www.moneynews.com  1394470372027

# justification of story prediction.


#`If you have only the story IDs and not the complete story texts, it may be more difficult to predict the categories of the stories based on their headlines alone. However, it may still be possible to perform some analysis using the available data.

One approach you could take is to try to extract some features from the headlines that may be indicative of the story category. For example, you could try using natural language processing techniques to extract named entities (such as people, organizations, and locations) from the headlines, or you could use sentiment analysis to determine the overall sentiment of the headline.

You could also try to use the available story IDs to link the headlines to other sources of information, such as external databases or websites, that may provide additional context about the stories and their categories.

      However, it's important to keep in mind that the accuracy of any predictions based on incomplete or limited data may be lower than if you had access to the complete story texts. It's also possible that some categories may be more difficult to predict based on the available data than others. Therefore, it's important to evaluate the performance of any analysis or predictions using appropriate metrics and to interpret the results with caution.






In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422419 entries, 0 to 422418
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   ID         422419 non-null  int64 
 1   TITLE      422419 non-null  object
 2   URL        422419 non-null  object
 3   PUBLISHER  422417 non-null  object
 4   CATEGORY   422419 non-null  object
 5   STORY      422419 non-null  object
 6   HOSTNAME   422419 non-null  object
 7   TIMESTAMP  422419 non-null  int64 
dtypes: int64(2), object(6)
memory usage: 25.8+ MB


In [5]:
len(df['CATEGORY'].unique())

4

In [7]:
df["STORY"].unique()

array(['ddUyU0VZz0BRneMioxUPQVP6sIxvM', 'dPhGU51DcrolUIMxbRm0InaHGA2XM',
       'dxyGGb4iN9Cs9aMZTKQpJeoiQfruM', ...,
       'dBVS5US1PZ9v2EMxNEdykF9V-7PCM', 'dhhnSHVoyA7ENBM3boDX_D_-3PV6M',
       'dpcLMoJD69UYMXMxaoEFnWql9YjQM'], dtype=object)

In [7]:
df["STORY"].duplicated()

0         False
1          True
2          True
3          True
4          True
          ...  
422414     True
422415     True
422416     True
422417     True
422418     True
Name: STORY, Length: 422419, dtype: bool

In [8]:
#to find null values in the data
df.isnull().sum()

ID           0
TITLE        0
URL          0
PUBLISHER    2
CATEGORY     0
STORY        0
HOSTNAME     0
TIMESTAMP    0
dtype: int64

In [9]:
df.shape

(422419, 8)

In [10]:
#to find null values in the data
df.isnull().sum()

ID           0
TITLE        0
URL          0
PUBLISHER    2
CATEGORY     0
STORY        0
HOSTNAME     0
TIMESTAMP    0
dtype: int64

In [11]:
#to remove null values
df.dropna(subset=["PUBLISHER"], axis=0, inplace=True)

In [12]:
#checking deleted null values
df.isnull().sum().to_frame().T

ID  TITLE  URL  PUBLISHER  CATEGORY  STORY  HOSTNAME  TIMESTAMP
0   0      0    0          0         0      0         0          0

In [13]:
df = pd.DataFrame(df)

# Set the 'name' column as the index
df.set_index('ID', inplace=True)

# Print the index of the DataFrame
print(df.index)

Int64Index([     1,      2,      3,      4,      5,      6,      7,      8,
                 9,     10,
            ...
            422928, 422929, 422930, 422931, 422932, 422933, 422934, 422935,
            422936, 422937],
           dtype='int64', name='ID', length=422417)


In [14]:
#using sklearn for machine learning algorithums

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression





In [15]:
#split the deta set innto training and testing deta sets
X_train, X_test, y_train, y_test = train_test_split(df['TITLE'], df['STORY'])

In [16]:
X_train.head()

ID
78311              General Motors issues another new recall
223811    Family of the missing MH370 pilot speaks in hi...
280045    'Jump Street' follow-up generates big laughs m...
25939     $1.2 billion Toyota penalty sends warning to a...
334426                   Is Danger Zone Inflation a Danger?
Name: TITLE, dtype: object

In [17]:
X_test.head()

ID
344621      Companies Add Most Workers Since 2012, ADP Says
190156    Willow Smith causes a stir with controversial ...
134898              Aereo: Bringing Network TV to Computers
187637    Miley Cyrus Resumes Her Bangerz Tour in London...
183541    'Orange is the New Black' Season 3 Announced b...
Name: TITLE, dtype: object

In [18]:
#Extract features from the headlines using a count vectorizer
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [19]:
print(X_train_vec, X_test_vec)

  (0, 19595)	1
  (0, 29495)	1
  (0, 24111)	1
  (0, 4900)	1
  (0, 30355)	1
  (0, 35908)	1
  (1, 17449)	1
  (1, 31236)	1
  (1, 43639)	1
  (1, 28936)	1
  (1, 28509)	1
  (1, 33309)	1
  (1, 41007)	1
  (1, 23083)	1
  (1, 21843)	1
  (1, 13423)	1
  (2, 24714)	1
  (2, 42012)	1
  (2, 18508)	1
  (2, 45935)	1
  (2, 19601)	1
  (2, 7214)	1
  (2, 25897)	1
  (2, 29090)	1
  (2, 39064)	1
  :	:
  (316809, 4041)	1
  (316809, 28672)	1
  (316809, 12877)	1
  (316809, 22194)	1
  (316809, 4412)	1
  (316809, 35759)	1
  (316809, 39167)	1
  (316810, 42012)	1
  (316810, 47060)	1
  (316810, 33889)	1
  (316810, 13036)	1
  (316810, 33007)	1
  (316811, 43639)	1
  (316811, 23083)	1
  (316811, 48326)	1
  (316811, 21994)	1
  (316811, 44233)	1
  (316811, 6385)	1
  (316811, 29233)	1
  (316811, 24559)	1
  (316811, 43007)	1
  (316811, 39141)	1
  (316811, 9724)	1
  (316811, 37585)	1
  (316811, 34535)	1   (0, 1224)	1
  (0, 3757)	1
  (0, 3871)	1
  (0, 11226)	1
  (0, 29447)	1
  (0, 38393)	1
  (0, 39896)	1
  (0, 48109)	1
  (1, 67

In [2]:
X_train

NameError: name 'X_train' is not defined

In [20]:
#train a logisticregressio model

model = LogisticRegression()
model.fit(X_train_vec, y_train)

#Evaluate the model on the testing set
score = model.score(X_train_vec, y_train)
print('Accuracy:', score)

MemoryError: Unable to allocate 17.0 GiB for an array with shape (316812, 7223) and data type int64

In [44]:
y_pred = model.predict(X_test_vec)

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# assume y_true and y_pred are the true and predicted labels respectively
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

# to get a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)

In [46]:
print(accuracy)
print(precision)
print(recall)
print(confusion_mat)

0.946460868330098
0.9457475692176986
0.9413011596158526
[[26926   448   256  1383]
 [  389 37469   120   299]
 [  353   245 10549   173]
 [ 1452   433   103 25007]]
